from __future__ import annotations

from collections.abc import Hashable, Iterable, Set
from typing import Any, Generic, TypeVar, overload

from typing_extensions import override

T = TypeVar("T", bound=Hashable)
T_cov = TypeVar("T_cov", covariant=True, bound=Hashable)

class InsOrderedSetIterator(Generic[T_cov]):
    def __iter__(self) -> InsOrderedSetIterator[T_cov]: ...
    def __next__(self) -> T_cov: ...

class OrderedSet(Generic[T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[T]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> InsOrderedSetIterator[T]: ...
    def __bool__(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: T) -> bool: ...
    def __lt__(self, other: T) -> bool: ...
    def __ge__(self, other: T) -> bool: ...
    def __gt__(self, other: T) -> bool: ...
    def add(self, key: T) -> None: ...
    def discard(self, key: T) -> None: ...
    def remove(self, key: T) -> None: ...
    def pop(self) -> T: ...
    def clear(self) -> None: ...
    def copy(self) -> OrderedSet[T]: ...
    def isdisjoint(self, other: Iterable[T]) -> bool: ...
    def issubset(self, other: Iterable[T]) -> bool: ...
    def issuperset(self, other: Iterable[T]) -> bool: ...
    def difference(self, *others: Iterable[T]) -> OrderedSet[T]: ...
    def intersection(self, *others: Iterable[T]) -> OrderedSet[T]: ...
    def union(self, *others: Iterable[T]) -> OrderedSet[T]: ...
    def symmetric_difference(self, other: Iterable[T]) -> OrderedSet[T]: ...
    def difference_update(self, *others: Iterable[T]) -> None: ...
    def intersection_update(self, *others: Iterable[T]) -> None: ...
    def symmetric_difference_update(self, other: Iterable[T]) -> None: ...
    def update(self, *others: Iterable[T]) -> None: ...
    def __and__(self, other: T) -> OrderedSet[T]: ...
    def __iand__(self, other: T) -> OrderedSet[T]: ...
    def __or__(self, other: T) -> OrderedSet[T]: ...
    def __ior__(self, other: T) -> OrderedSet[T]: ...
    def __sub__(self, other: T) -> OrderedSet[T]: ...
    def __isub__(self, other: T) -> OrderedSet[T]: ...
    def __xor__(self, other: T) -> OrderedSet[T]: ...
    def __ixor__(self, other: T) -> OrderedSet[T]: ...
    @override
    def __reduce__(self) -> tuple[type[OrderedSet[T]], tuple[list[T]]]: ...

class FrozenOrderedSet(Generic[T_cov]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[T_cov]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> InsOrderedSetIterator[T_cov]: ...
    def __bool__(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: Set[Any]) -> bool: ...
    def __lt__(self, other: Set[Any]) -> bool: ...
    def __ge__(self, other: Set[Any]) -> bool: ...
    def __gt__(self, other: Set[Any]) -> bool: ...
    def copy(self) -> FrozenOrderedSet[T_cov]: ...
    def isdisjoint(self, other: Iterable[T_cov]) -> bool: ...
    def issubset(self, other: Iterable[T_cov]) -> bool: ...
    def issuperset(self, other: Iterable[T_cov]) -> bool: ...
    def difference(self, *others: Iterable[T_cov]) -> FrozenOrderedSet[T_cov]: ...
    def intersection(self, *others: Iterable[T_cov]) -> FrozenOrderedSet[T_cov]: ...
    def union(self, *others: Iterable[T_cov]) -> FrozenOrderedSet[T_cov]: ...
    def symmetric_difference(
        self, other: Iterable[T_cov]
    ) -> FrozenOrderedSet[T_cov]: ...
    def __and__(self, other: Set[Any]) -> FrozenOrderedSet[T_cov]: ...
    def __or__(self, other: Set[Any]) -> FrozenOrderedSet[T_cov]: ...
    def __sub__(self, other: Set[Any]) -> FrozenOrderedSet[T_cov]: ...
    def __xor__(self, other: Set[Any]) -> FrozenOrderedSet[T_cov]: ...
    @override
    def __reduce__(
        self,
    ) -> tuple[type[FrozenOrderedSet[T_cov]], tuple[list[T_cov]]]: ...
