
from __future__ import annotations

from typing import Any, Iterable, overload

class InsOrderedSetIterator:
    def __iter__(self) -> InsOrderedSetIterator: ...
    def __next__(self) -> Any: ...

class OrderedSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Any]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> InsOrderedSetIterator: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def add(self, key: Any) -> None:
        ...

    def discard(self, key: Any) -> None:
        ...

    def remove(self, key: Any) -> None:
        ...

    def pop(self) -> Any:
        ...

    def clear(self) -> None:
        ...

    def copy(self) -> OrderedSet:
        ...

    def isdisjoint(self, other: Iterable[Any]) -> bool:
        ...

    def issubset(self, other: Iterable[Any]) -> bool:
        ...

    def issuperset(self, other: Iterable[Any]) -> bool:
        ...

    def difference(self, *others: Iterable[Any]) -> OrderedSet:
        ...

    def intersection(self, *others: Iterable[Any]) -> OrderedSet:
        ...

    def union(self, *others: Iterable[Any]) -> OrderedSet:
        ...

    def symmetric_difference(self, other: Iterable[Any]) -> OrderedSet:
        ...

    def difference_update(self, *others: Iterable[Any]) -> None:
        ...

    def intersection_update(self, *others: Iterable[Any]) -> None:
        ...

    def symmetric_difference_update(self, other: Iterable[Any]) -> None:
        ...

    def update(self, *others: Iterable[Any]) -> None:
        ...

    def __and__(self, other: Any) -> OrderedSet: ...
    def __iand__(self, other: Any) -> OrderedSet: ...
    def __or__(self, other: Any) -> OrderedSet: ...
    def __ior__(self, other: Any) -> OrderedSet: ...
    def __sub__(self, other: Any) -> OrderedSet: ...
    def __isub__(self, other: Any) -> OrderedSet: ...
    def __xor__(self, other: Any) -> OrderedSet: ...
    def __ixor__(self, other: Any) -> OrderedSet: ...
    def __reduce__(self) -> tuple[type[OrderedSet], tuple[list[Any]]]: ...

class FrozenOrderedSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Any]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> InsOrderedSetIterator: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def copy(self) -> FrozenOrderedSet:
        ...

    def isdisjoint(self, other: Iterable[Any]) -> bool:
        ...

    def issubset(self, other: Iterable[Any]) -> bool:
        ...

    def issuperset(self, other: Iterable[Any]) -> bool:
        ...

    def difference(self, *others: Iterable[Any]) -> FrozenOrderedSet:
        ...

    def intersection(self, *others: Iterable[Any]) -> FrozenOrderedSet:
        ...

    def union(self, *others: Iterable[Any]) -> FrozenOrderedSet:
        ...

    def symmetric_difference(self, other: Iterable[Any]) -> FrozenOrderedSet:
        ...

    def __and__(self, other: Any) -> FrozenOrderedSet: ...
    def __or__(self, other: Any) -> FrozenOrderedSet: ...
    def __sub__(self, other: Any) -> FrozenOrderedSet: ...
    def __xor__(self, other: Any) -> FrozenOrderedSet: ...
    def __reduce__(self) -> tuple[type[FrozenOrderedSet], tuple[list[Any]]]: ...
