"""Type stubs for the _insorderset_core C extension."""

from __future__ import annotations

from typing import Any, Iterable, overload

class InsOrderedSetIterator:
    """Iterator over the elements of an :class:`OrderedSet` or
    :class:`FrozenOrderedSet` in insertion order."""

    def __iter__(self) -> InsOrderedSetIterator: ...
    def __next__(self) -> Any: ...

class OrderedSet:
    """Mutable insertion-ordered set.

    A drop-in replacement for :class:`set` that preserves insertion order.
    Elements must be hashable. Unlike :class:`set`, iteration always yields
    elements in the order they were first inserted.

    :class:`OrderedSet` is **not** hashable (like :class:`set`).
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Any]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> InsOrderedSetIterator: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    __hash__: None
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def add(self, key: Any) -> None:
        """Add *key* to the set. No-op if *key* is already present."""
        ...

    def discard(self, key: Any) -> None:
        """Remove *key* from the set if it is present. No-op otherwise."""
        ...

    def remove(self, key: Any) -> None:
        """Remove *key* from the set.

        :raises KeyError: if *key* is not present.
        """
        ...

    def pop(self) -> Any:
        """Remove and return the last-inserted element.

        :raises KeyError: if the set is empty.
        """
        ...

    def clear(self) -> None:
        """Remove all elements from the set."""
        ...

    def copy(self) -> OrderedSet:
        """Return a shallow copy of the set."""
        ...

    def isdisjoint(self, other: Iterable[Any]) -> bool:
        """Return ``True`` if the set has no elements in common with *other*."""
        ...

    def issubset(self, other: Iterable[Any]) -> bool:
        """Test whether every element of the set is in *other*."""
        ...

    def issuperset(self, other: Iterable[Any]) -> bool:
        """Test whether every element of *other* is in the set."""
        ...

    def difference(self, *others: Iterable[Any]) -> OrderedSet:
        """Return a new set with elements not in any of *others*."""
        ...

    def intersection(self, *others: Iterable[Any]) -> OrderedSet:
        """Return a new set with elements common to the set and all *others*."""
        ...

    def union(self, *others: Iterable[Any]) -> OrderedSet:
        """Return a new set with elements from the set and all *others*."""
        ...

    def symmetric_difference(self, other: Iterable[Any]) -> OrderedSet:
        """Return a new set with elements in either set but not both."""
        ...

    def difference_update(self, *others: Iterable[Any]) -> None:
        """Remove all elements found in *others* from the set in place."""
        ...

    def intersection_update(self, *others: Iterable[Any]) -> None:
        """Retain only elements also found in all *others*, in place."""
        ...

    def symmetric_difference_update(self, other: Iterable[Any]) -> None:
        """Update set to the symmetric difference with *other*, in place."""
        ...

    def update(self, *others: Iterable[Any]) -> None:
        """Add all elements from *others* to the set in place."""
        ...

    def __and__(self, other: Any) -> OrderedSet: ...
    def __iand__(self, other: Any) -> OrderedSet: ...
    def __or__(self, other: Any) -> OrderedSet: ...
    def __ior__(self, other: Any) -> OrderedSet: ...
    def __sub__(self, other: Any) -> OrderedSet: ...
    def __isub__(self, other: Any) -> OrderedSet: ...
    def __xor__(self, other: Any) -> OrderedSet: ...
    def __ixor__(self, other: Any) -> OrderedSet: ...
    def __reduce__(self) -> tuple[type[OrderedSet], tuple[list[Any]]]: ...

class FrozenOrderedSet:
    """Immutable insertion-ordered set.

    A drop-in replacement for :class:`frozenset` that preserves insertion
    order. Elements must be hashable. Unlike :class:`frozenset`, iteration
    always yields elements in the order they were first inserted.

    :class:`FrozenOrderedSet` is hashable with the same hash value as the
    equivalent :class:`frozenset`, so it can be used as a dictionary key or
    placed inside another set. The hash is computed lazily and cached.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Any]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> InsOrderedSetIterator: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def copy(self) -> FrozenOrderedSet:
        """Return a shallow copy of the set."""
        ...

    def isdisjoint(self, other: Iterable[Any]) -> bool:
        """Return ``True`` if the set has no elements in common with *other*."""
        ...

    def issubset(self, other: Iterable[Any]) -> bool:
        """Test whether every element of the set is in *other*."""
        ...

    def issuperset(self, other: Iterable[Any]) -> bool:
        """Test whether every element of *other* is in the set."""
        ...

    def difference(self, *others: Iterable[Any]) -> FrozenOrderedSet:
        """Return a new set with elements not in any of *others*."""
        ...

    def intersection(self, *others: Iterable[Any]) -> FrozenOrderedSet:
        """Return a new set with elements common to the set and all *others*."""
        ...

    def union(self, *others: Iterable[Any]) -> FrozenOrderedSet:
        """Return a new set with elements from the set and all *others*."""
        ...

    def symmetric_difference(self, other: Iterable[Any]) -> FrozenOrderedSet:
        """Return a new set with elements in either set but not both."""
        ...

    def __and__(self, other: Any) -> FrozenOrderedSet: ...
    def __or__(self, other: Any) -> FrozenOrderedSet: ...
    def __sub__(self, other: Any) -> FrozenOrderedSet: ...
    def __xor__(self, other: Any) -> FrozenOrderedSet: ...
    def __reduce__(self) -> tuple[type[FrozenOrderedSet], tuple[list[Any]]]: ...
